# build variables
os: Visual Studio 2015
configuration: Release
platform: Any CPU
environment:
  version: 1.1.0.42
  ApiKey:
    secure: wxXXl1PMM1ifiplhjL4+s0Djdx9B/Nx1yZq6xpyWlNIeJR/QArveSDAefkWlYwdO
  
# versioning
version: $(version)-{build}

# build
branches:
  only:
    - master
build_script: 
  - ps: >-
      choco pack ./xamarin-component.nuspec --version $env:version;
      
# tests
test_script:
  - ps: >-
      choco install xamarin-component -fdvy -s .;
      where xamarin-component;
      xamarin-component help;
  
# artifacts
artifacts: 
  - path: xamarin-component.$(version).nupkg

# deployment
deploy_script:
  - ps: >-
      choco push -k="$env:ApiKey"
